---
 - name: This is final
   ec2_instance_facts:
    region: "us-east-1"
  #  filters:
  #     "tag:Name": Webserver

   register: ec2_metadata

 - debug: msg="{{ ec2_metadata.instances }}"
 - debug: msg="{{ ec2_metadata.instances[0].client_token }}"
 - debug: msg="{{ ec2_metadata.instances[0].instance_id }}"

 - name: This is a simple test
   debug: var=item
   with_items: "{{ ec2_metadata.instances[1].instance_id }}"

 - name: This is a simple test 1
   debug: msg="{{ item['instance_id'] }}"
   with_items: "{{ ec2_metadata.instances }}"

 - name: terminating single instance
   local_action:
     module: ec2
     state: 'absent'
     region: us-east-1
     instance_ids: "{{ item['instance_id'] }}"
   with_items: "{{ ec2_metadata.instances }}"
